[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mlprojects"
version = "0.0.1"
description = "Little ML projects for learning"
readme = "README.md"
requires-python = ">=3.10"
